### PR TITLE
AXIOS error 403 fixed

### PR DESCRIPTION
**Pull request by acessrdpgg**
used fetch instead of axios requests to fix the issue

image

### CODE REVIEW

**Comment by Freddywhest** [comment]
Still not working for some people

**Comment by acessrdpgg** [comment]
> Still not working for some people

Yeah, its seems like they are flagging some IP's as blacklisted, the only option left now is to either use proxies, or use cloudflare bypass APIs which are not free to use. I'm trying to find a way, will update ASAP

**Comment by Freddywhest** [comment]
I develop a library to fix it

**Comment by Freddywhest** [comment]
The issue left is how to avoid Flood, if you have any idea you can share it

**Comment by acessrdpgg** [comment]
> I developed a library (fdy-scraping) to fix it

The main issue for that 403 was just headers, i made a pull request by tweaking the headers a bit and it worked fine even with multiple sessions, but your library also fix the issue neatly great work :)

**Comment by acessrdpgg** [comment]
> The issue left is how to avoid Flood, if you have any idea you can share it

Couldn't find a way to reproduce it, i tried with 7 accounts none of them gave flood however.

**Comment by Freddywhest** [comment]
Alright, thanks man

**Pull request merged**
